<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Tue, 05 Sep 2017 15:41:45 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['PmaAbsoluteUri'] = 'http://localhost/phpmyadmin/';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'Fk.-9(wm^}#.-aM|Wwlvd!1oSC=max(A';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>